[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['npm install -g corepack && corepack enable', 'yarn install --update-lockfile']

[phases.build]
cmd = 'yarn nx run backend:build:production'

[start]
cmd = 'yarn nx run backend:start:production'
